name: Tests
on:
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
      - uses: gradle/gradle-build-action@v2
      - name: Execute Gradle build
        working-directory: ./backend
        run: ./gradlew check
        env:
          OAUTH_JWTKS_URL: ${{ secrets.OAUTH_JWTKS_URL }}
  e2e:
    name: e2e
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Gradle build
        working-directory: ./backend
        run: ./gradlew assemble
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: e2e
        run: npm i && npm run build-dev && npm run e2e-ci
        working-directory: frontend
        env:
          OAUTH_CLIENT_ID: ${{ secrets.OAUTH_CLIENT_ID }}
          OAUTH_CLIENT_SECRET: ${{ secrets.OAUTH_CLIENT_SECRET }}
          OAUTH_DOMAIN: ${{ secrets.OAUTH_DOMAIN }}
      - uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
          name: e2e-video
          path: frontend/cypress/videos/*

