name: Update Angular
on:
   schedule:
     - cron: '30 0 1 * *'
  workflow_dispatch:
jobs:
  update:
    name: Updates Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Angular update
        working-directory: frontend
        run: | 
          npm i
          npm run ng update
          npm run ng update @angular/cli @angular/core
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Upgraded to Angular ${{ steps.xpath.outputs.result }}
          title: '[Upgrade] Upgraded to Angular ${{ steps.xpath.outputs.result }}'
          body: |
            There is a newer version ${{ steps.xpath.outputs.result }} of Angular available. The dependency has been updated and the inspection tools
            have been regenerated.
          labels: chore,upgrade
          assignees: adrienpessu
          branch: upgrade/angular
      - name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
      - name: Enable Automerge
        run: gh pr merge --auto --merge "$PR_URL" | echo 0
        env:
          PR_URL: ${{ steps.cpr.outputs.pull-request-url }}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
