name: Update Angular
on:
  schedule:
    - cron: '30 0 * * *'
  workflow_dispatch:
jobs:
  update:
    name: Updates Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Angular update
        working-directory: frontend
        run: | 
          npm i
          npm run ng update
          npm run ng update @angular/cli @angular/core
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Upgraded to Angular ${{ steps.xpath.outputs.result }}
          title: '[Upgrade] Upgraded to Angular ${{ steps.xpath.outputs.result }}'
          body: |
            There is a newer version ${{ steps.xpath.outputs.result }} of Angular available. The dependency has been updated and the inspection tools
            have been regenerated.
          labels: chore,upgrade
          assignees: adrienpessu
          branch: upgrade/angular
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
